name: cbiztest
favicon: null
layout_spectrum: 0.9800486941821873
typography_spectrum: 0.82759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#009ed7'
    - '#535353'
    - '#74cbe8'
  brandStrength: 1
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
